table governance_inventory
	lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0300

	/// The scan run identifier. One value per scan; new snapshots are appended so inventory can be trended.
	column 'Run ID'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0301
		summarizeBy: none
		sourceColumn: run_id

		annotation SummarizationSetBy = Automatic

	/// ISO-8601 UTC timestamp of the inventory snapshot. Stored as text; sorts chronologically.
	column 'Timestamp'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0302
		summarizeBy: none
		sourceColumn: timestamp

		annotation SummarizationSetBy = Automatic

	/// Resource kind: Workspace | Personal Workspace | Capacity | Domain.
	column 'Resource type'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0303
		summarizeBy: none
		sourceColumn: resource_type

		annotation SummarizationSetBy = Automatic

	column 'Resource ID'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0304
		summarizeBy: none
		sourceColumn: resource_id

		annotation SummarizationSetBy = Automatic

	column 'Name'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0305
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	/// Lifecycle state of the resource (e.g. Active, Deleted, Paused).
	column 'State'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0306
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column 'SKU'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0307
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column 'Region'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0308
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column 'On dedicated capacity'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0309
		summarizeBy: none
		sourceColumn: on_dedicated_capacity

		annotation SummarizationSetBy = Automatic

	column 'Capacity'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e030a
		summarizeBy: none
		sourceColumn: capacity_name

		annotation SummarizationSetBy = Automatic

	column 'Domain'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e030b
		summarizeBy: none
		sourceColumn: domain_name

		annotation SummarizationSetBy = Automatic

	column 'Admins'
		dataType: int64
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e030c
		summarizeBy: none
		sourceColumn: admin_count

		annotation SummarizationSetBy = Automatic

	column 'Users'
		dataType: int64
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e030d
		summarizeBy: none
		sourceColumn: user_count

		annotation SummarizationSetBy = Automatic

	/// Whether the resource is orphaned/unused (Yes | No).
	column 'Orphaned'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e030e
		summarizeBy: none
		sourceColumn: is_orphan

		annotation SummarizationSetBy = Automatic

	/// Comma-separated reasons the resource was flagged as orphaned/unused.
	column 'Why flagged'
		dataType: string
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e030f
		summarizeBy: none
		sourceColumn: orphan_reasons

		annotation SummarizationSetBy = Automatic

	/// --- Latest-snapshot inventory measures (current state) --------------------

	/// run_id of the most recent inventory snapshot; anchors the current-state counts.
	measure 'Latest Inventory Run ID' = ```
			VAR MaxTs = MAX ( governance_inventory[Timestamp] )
			RETURN
			    CALCULATE (
			        SELECTEDVALUE ( governance_inventory[Run ID] ),
			        FILTER ( ALL ( governance_inventory ), governance_inventory[Timestamp] = MaxTs )
			    )
			```
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0400

	measure 'Resources (Latest Run)' = ```
			VAR lr = [Latest Inventory Run ID]
			RETURN
			    CALCULATE ( COUNTROWS ( governance_inventory ), governance_inventory[Run ID] = lr )
			```
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0401

	measure 'Orphaned Resources (Latest Run)' = CALCULATE ( [Resources (Latest Run)], KEEPFILTERS ( governance_inventory[Orphaned] = "Yes" ) )
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0402

	measure 'Workspaces (Latest Run)' = CALCULATE ( [Resources (Latest Run)], KEEPFILTERS ( governance_inventory[Resource type] = "Workspace" ) )
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0403

	measure 'Capacities (Latest Run)' = CALCULATE ( [Resources (Latest Run)], KEEPFILTERS ( governance_inventory[Resource type] = "Capacity" ) )
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0404

	measure 'Domains (Latest Run)' = CALCULATE ( [Resources (Latest Run)], KEEPFILTERS ( governance_inventory[Resource type] = "Domain" ) )
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0405

	/// Capacities in the latest snapshot with no workspaces assigned (candidates to pause or remove).
	measure 'Capacities Without Workspaces (Latest Run)' = ```
			VAR lr = [Latest Inventory Run ID]
			RETURN
			    CALCULATE (
			        COUNTROWS ( governance_inventory ),
			        governance_inventory[Run ID] = lr,
			        governance_inventory[Resource type] = "Capacity",
			        CONTAINSSTRING ( governance_inventory[Why flagged], "no-workspaces-assigned" )
			    )
			```
		formatString: 0
		lineageTag: 6c4b2d33-1e55-4f88-ab21-9a3c7d2e0406

	partition governance_inventory = entity
		mode: directLake
		source
			entityName: governance_inventory
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table
